
export const GET_SERVICE_REQUESTED = 'ServiceState/GET_SERVICE_REQUESTED'
export const GET_SERVICE_SUCCESS = 'ServiceState/GET_SERVICE_SUCCESS'
export const GET_SERVICE_FAILED = 'ServiceState/GET_SERVICE_FAILED'
export const SAVE_SERVICE_REQUESTED = 'ServiceState/SAVE_SERVICE_REQUESTED'
export const SAVE_SERVICE_SUCCESS = 'ServiceState/SAVE_SERVICE_SUCCESS'
export const SAVE_SERVICE_FAILED = 'ServiceState/SAVE_SERVICE_FAILED'
export const CHANGE_CITY = 'ServiceState/CHANGE_CITY'
export const CHANGE_SEARCH_TEXT = 'ServiceState/CHANGE_SEARCH_TEXT'
export const CHANGE_LABEL = 'ServiceState/CHANGE_LABEL'
export const GOT_SERVICE_DATA = 'ServiceState/GOT_SERVICE_DATA'
export const CHANGE_CATEGORY = 'ServiceState/CHANGE_CATEGORY'

export const GET_BANNER_REQUESTED = 'ExtraState/GET_BANNER_REQUESTED'
export const GET_BANNER_SUCCESS = 'ExtraState/GET_BANNER_SUCCESS'
export const GET_BANNER_FAILED = 'ExtraState/GET_BANNER_FAILED'

export const GET_UI_WORDS_REQUESTED = 'ExtraState/GET_UI_WORDS_REQUESTED'
export const GET_UI_WORDS_SUCCESS = 'ExtraState/GET_UI_WORDS_SUCCESS'
export const GET_UI_WORDS_FAILED = 'ExtraState/GET_UI_WORDS_FAILED'

export const SIGNUP_USER_REQUESTED = 'UserState/SIGNUP_USER_REQUESTED'
export const SIGNUP_USER_SUCCESS = 'UserState/SIGNUP_USER_SUCCESS'
export const SIGNUP_USER_FAILED = 'UserState/SIGNUP_USER_FAILED'

export const GET_CAR_CATEGORY_REQUESTED = 'UserState/GET_CAR_CATEGORY_REQUESTED'
export const GET_CAR_CATEGORY_SUCCESS = 'UserState/GET_CAR_CATEGORY_SUCCESS'
export const GET_CAR_CATEGORY_FAILED = 'UserState/GET_CAR_CATEGORY_FAILED'

export const ADD_CAR_REQUESTED = 'UserState/ADD_CAR_REQUESTED'
export const ADD_CAR_SUCCESS = 'UserState/ADD_CAR_SUCCESS'
export const ADD_CAR_FAILED = 'UserState/ADD_CAR_FAILED'

export const GET_CAR_REQUESTED = 'UserState/GET_CAR_REQUESTED'
export const GET_CAR_SUCCESS = 'UserState/GET_CAR_SUCCESS'
export const GET_CAR_FAILED = 'UserState/GET_CAR_FAILED'

export const SIGNIN_USER_REQUESTED = 'UserState/SIGNIN_USER_REQUESTED'
export const SIGNIN_USER_SUCCESS = 'UserState/SIGNIN_USER_SUCCESS'
export const SIGNIN_USER_FAILED = 'UserState/SIGNIN_USER_FAILED'

export const GET_VERIFY_CODE_REQUEST = 'UserState/GET_VERIFY_CODE_REQUEST'
export const GET_VERIFY_CODE_SUCCESS = 'UserState/GET_VERIFY_CODE_SUCCESS'
export const GET_VERIFY_CODE_FAILED = 'UserState/GET_VERIFY_CODE_FAILED'

export const SET_USER_LOCATION = 'UserState/SET_USER_LOCATION'

export const CLEAR_ERROR_USER = 'UserState/CLEAR_ERROR_USER'
export const CLEAR_VERIFY_CODE = 'UserState/CLEAR_VERIFY_CODE'

export const GET_EXPERT_DATA_REQUESTED = 'ExpertState/GET_EXPERT_DATA_REQUESTED'
export const GET_EXPERT_DATA_SUCCESS = 'ExpertState/GET_EXPERT_DATA_SUCCESS'
export const GET_EXPERT_DATA_FAILED = 'ExpertState/GET_EXPERT_DATA_FAILED'
export const CLEAR_EXPERT_STATE = 'ExpertState/CLEAR_EXPERT_STATE'

export const GET_TECHNICIAN_DATA_REQUESTED = 'TechnicianState/GET_TECHNICIAN_DATA_REQUESTED'
export const GET_TECHNICIAN_DATA_SUCCESS = 'TechnicianState/GET_TECHNICIAN_DATA_SUCCESS'
export const GET_TECHNICIAN_DATA_FAILED = 'TechnicianState/GET_TECHNICIAN_DATA_FAILED'
export const CLEAR_TECHNICIAN_STATE = 'TechnicianState/CLEAR_TECHNICIAN_STATE'

export const GET_COMMENT_DATA_REQUESTED = 'CommentState/GET_COMMENT_DATA_REQUESTED'
export const GET_COMMENT_DATA_SUCCESS = 'CommentState/GET_COMMENT_DATA_SUCCESS'
export const GET_COMMENT_DATA_FAILED = 'CommentState/GET_COMMENT_DATA_FAILED'
export const CLEAR_COMMENT_STATE = 'CommentState/CLEAR_COMMENT_STATE'

export const CHANGE_PASSWORD_REQUESTED = 'UserState/CHANGE_PASSWORD_REQUESTED'
export const CHANGE_PASSWORD_SUCCESS = 'UserState/CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_FAILED = 'UserState/CHANGE_PASSWORD_FAILED'

export const SIGN_OUT = 'UserState/SIGN_OUT'
